version: "3"
services:
  react_frontend:
    build:
      context: ./react-frontend
      dockerfile: Dockerfile
    ports:
      - "4181:4181"
    volumes:
      - ./react-frontend:/app
    depends_on:
      - node_server

  node_server:
    build:
      context: ./node-server
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - ./data:/app/data
      - ./node-server:/app
    depends_on:
      - fluree

  fluree:
    image: fluree/http-api-gateway:latest
    ports:
      - "58090:8090"
    volumes:
      - "./data:/opt/fluree-http-api-gateway/data"

